[package]
name = "eth_pools"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.9"}
alloy-provider = "1.0.9"
alloy-sol-types = "1.0.9"
alloy-contract = "1.0.9"
anyhow = "1.0.98"
tokio = { version = "1", features = ["macros"] }
futures = "0.3.31"
